version: '3.12'
services:
  django:
    container_name: mr-analyzer
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
