# Generated by Django 5.0.3 on 2024-03-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='choosenoption',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
