# Generated by Django 5.0.3 on 2024-06-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rockmine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauploadmodel',
            name='data',
            field=models.TextField(),
        ),
    ]
