# Generated by Django 5.0.3 on 2024-07-24 17:14

import asktoaske.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asktoaske', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), asktoaske.models.validate_file_size]),
        ),
    ]
