# Generated by Django 5.0.3 on 2024-06-13 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancies', models.IntegerField()),
                ('glucose', models.IntegerField()),
                ('blood_pressure', models.IntegerField()),
                ('insulin', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('dbf', models.FloatField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
