# Generated by Django 5.0.3 on 2024-06-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datauploadmodel',
            name='skin_thickness',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
