# Generated by Django 5.0.3 on 2024-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQgenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasenamemodel',
            name='nos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
