# Generated by Django 5.0.3 on 2024-06-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='top10alltime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=500)),
                ('released_date', models.DateField()),
                ('runtime', models.IntegerField(default=0)),
            ],
        ),
    ]
