# Generated by Django 5.0.3 on 2024-06-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviesystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
    ]
